---
title: "Data & Sources"
---

__Data__

The tidy dataset used for this analysis includes the position and department affiliation of 392 faculty signatories (as of 12/03/16). Where faculty listed multiple department affiliations, in almost all cases, the first one listed was maintained. Department affiliations and position categories were combined where appropriate (e.g. neurobiology was coded as biology and uniquely named professorships were binned into a single category).

***

__Catalog__ 

_Positions_

* Harper Fellow 
* Provost's Postdoctoral Scholar 
* Lecturer 
* Senior Lecturer 
* Assistant Clinical Professor 
* Clinical Professor 
* Assistant Professor 
* Associate Professor 
* Professor 
* Distinguished Service Professor 
* Named Professor 
* Professor Emeritus 
* Visiting Lecturer 
* Visiting Professor 
* Executive Director 

_Departments_ 

* English                                     
* Comparative Human Development               
* Visual Arts                                 
* History                                     
* Divinity                                    
* Philosophy                                  
* Social Sciences Administration              
* Comparative Literature                      
* Creative Writing                            
* Law                                         
* Medicine                                    
* Art History                                 
* Political Science                           
* Anthropology                                
* Romance Languages and Literatures           
* Linguistics                                 
* Human Genetics                              
* Music                                       
* Humanities                                  
* Social Sciences Division                    
* Sociology                                   
* South Asian Languages and Literatures       
* Near East Languages and Civilizations       
* Psychiatry                                  
* Computer Science                            
* Physics                                     
* Statistics                                  
* East Asian Languages and Civilizations      
* Cinema and Media Studies                    
* Classics                                    
* Germanic Studies                            
* Slavic                                      
* Social Thought                              
* Young Center for Immigrant Children's Rights
* Society of Fellows                          
* French                                      
* Business                                    
* Biology                                     
* Mathematics                                 
* Psychology                                  
* Institute for Molecular Engineering         
* Human Rights                                
* Public Policy                               

***

Data Sources:
["Letter to University of Chicago Administration Concerning Changes to U.S. Immigration Policy"](https://docs.google.com/forms/d/e/1FAIpQLSdozFBhNzeHZPQAywaxG9YHOx9BYBxL3dxPyDXFPV6fXIbuqg/viewform?c=0&w=1)  

[Tenure Status Classification](https://provost.uchicago.edu/handbook/academic-appointments/ranks-statute-11)  

[Deparment Faculty Rosters](https://directory.uchicago.edu/organizations/search)