---
title: "An Inquiry into Faculty Activism"
---

Student activism is covered a lot
Faculty activism less so

Taking a recent petition as the departure point for the analysis, what factors influence faculty activism?
  How does tenure influence it? 
  How does department affiliation affect it? 

Clear that some departments made a more concerted effort - forwarded through listservs

Questions for future research: 
  How does participation vary based on type of petition? 
  What is the role of someone sending it through a faculty listserv? 



Has Tenure | Tenure Track | Non-Tenure | Not Listed
------------- | ------------- | ------------- | -------------
251 | 79 | 46 | 16



I selected 6 departments from the range of formal academic divisions across the university: statistics, romance languages, philosophy, statistics, human genetics, computer science. 

I created a dataset of all faculty from these departments using the university directory and coded whether or not the individual signed the letter. 





